### ISSUE TITLE
Issues running PB Honey with blars 5.3.2

### ISSUE THREAD

**Issue by unnatisonawala** [dbrowneup/PBSuite#3]
Even with the edited scripts to work with the newer versions of blasr I keep running into the following error:
ERROR: -nproc is not a valid option.

I tried looking through the scripts to see if the -nrpoc wasn't changed to --nproc, but couldn't find any. 
Has anyone else had this issue? What did you do to troubleshoot it? 
Thanks.

**Comment by biozhangzhou** [comment]
Please change all the blasr related scripts code into blasr 5.3.2 style.
